# Generated by Django 4.0.2 on 2022-03-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyCludUser',
            new_name='MyClubUser',
        ),
    ]
